version: "2"
services:
  metadata-store:
    container_name: postgres
    image: postgres:11.2
    environment:
      - POSTGRES_USER=druid
      - POSTGRES_PASSWORD=mysecretpassword


  zookeeper:
    container_name: zookeeper
    image: zookeeper
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=zookeeper

  coordinator:
    image: confluentinc/cc-druid:v0.0.1-0.14.0
    ports:
      - "8081:8081"
    environment:
      - ZOOKEEPER_HOST=zookeeper
      - DB_TYPE=postgresql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DBNAME=druid
      - DB_USERNAME=druid
      - DB_PASSWORD=mysecretpassword
      - S3_STORAGE_BUCKET=your-deep-storage-bucket-goes-here
      - S3_INDEXING_BUCKET=your-index-log-bucket-goes-here
      - S3_ACCESS_KEY=XXXXXXXXXXXXXXXXXXXX
      - S3_SECRET_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    command:
      - coordinator

  broker:
    image: confluentinc/cc-druid:v0.0.1-0.14.0
    ports:
      - "8082:8082"
    environment:
      - ZOOKEEPER_HOST=zookeeper
      - DB_TYPE=postgresql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DBNAME=druid
      - DB_USERNAME=druid
      - DB_PASSWORD=mysecretpassword
      - S3_STORAGE_BUCKET=your-deep-storage-bucket-goes-here
      - S3_INDEXING_BUCKET=your-index-log-bucket-goes-here
      - S3_ACCESS_KEY=XXXXXXXXXXXXXXXXXXXX
      - S3_SECRET_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    command:
      - broker

  historical:
    image: confluentinc/cc-druid:v0.0.1-0.14.0
    ports:
      - "8083:8083"
    environment:
      - ZOOKEEPER_HOST=zookeeper
      - DB_TYPE=postgresql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DBNAME=druid
      - DB_USERNAME=druid
      - DB_PASSWORD=mysecretpassword
      - S3_STORAGE_BUCKET=your-deep-storage-bucket-goes-here
      - S3_INDEXING_BUCKET=your-index-log-bucket-goes-here
      - S3_ACCESS_KEY=XXXXXXXXXXXXXXXXXXXX
      - S3_SECRET_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    command:
      - historical

  overlord:
    image: confluentinc/cc-druid:v0.0.1-0.14.0
    ports:
      - "8090:8090"
    environment:
      - ZOOKEEPER_HOST=zookeeper
      - DB_TYPE=postgresql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DBNAME=druid
      - DB_USERNAME=druid
      - DB_PASSWORD=mysecretpassword
      - S3_STORAGE_BUCKET=your-deep-storage-bucket-goes-here
      - S3_INDEXING_BUCKET=your-index-log-bucket-goes-here
      - S3_ACCESS_KEY=XXXXXXXXXXXXXXXXXXXX
      - S3_SECRET_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    command:
      - overlord

  middlemanager:
    image: confluentinc/cc-druid:v0.0.1-0.14.0
    ports:
      - "8091:8091"
    environment:
      - ZOOKEEPER_HOST=zookeeper
      - DB_TYPE=postgresql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DBNAME=druid
      - DB_USERNAME=druid
      - DB_PASSWORD=mysecretpassword
      - S3_STORAGE_BUCKET=your-deep-storage-bucket-goes-here
      - S3_INDEXING_BUCKET=your-index-log-bucket-goes-here
      - S3_ACCESS_KEY=XXXXXXXXXXXXXXXXXXXX
      - S3_SECRET_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    command:
      - middleManager

  router:
    image: confluentinc/cc-druid:v0.0.1-0.14.0
    ports:
      - "8888:8888"
    environment:
      - ZOOKEEPER_HOST=zookeeper
      - DB_TYPE=postgresql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DBNAME=druid
      - DB_USERNAME=druid
      - DB_PASSWORD=mysecretpassword
      - S3_STORAGE_BUCKET=your-deep-storage-bucket-goes-here
      - S3_INDEXING_BUCKET=your-index-log-bucket-goes-here
      - S3_ACCESS_KEY=XXXXXXXXXXXXXXXXXXXX
      - S3_SECRET_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    command:
      - router
